name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
#        with: 
#          ref: ${{ github.workspace }}
      
      - name: Request action 
        uses: fjogeleit/http-request-action@master
        with: 
          url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
          method: 'POST'
          contentType: application/json
            #          data: '{ "key": "value" }'
          files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
