name: test-POST 
on: [push]
jobs:
  post_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd "${GITHUB_WORKSPACE}"
      - run: curl -d @test.json -H "Content-Type: application/json" -X POST "https://tumgi3.free.beeceptor.com/test"
