name: test-POST 
on: [push]
jobs:
  post_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -d "@$i{GITHUB_WORKSPACE}/test.json" -H "Content-Type: application/json" -X POST https://tumgi3.free.beeceptor.com
