name: test-POST 
on: [push]
#env:
#  mapping_json: $((cat ./mappings.json) 2>&1)
#  mapping_json: 'temporar'
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: step_two
        run: |
          MAPPING_JSON=$((cat ./mappings.json) 2>&1) 
          echo $MAPPING_JSON

      - name: post mapping
        uses: fjogeleit/http-request-action@master
        with: 
          #       url: "https://tumgi3.free.beeceptor.com/my/api/path"
          url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
          method: 'POST'
          data: ${{ env.MAPPING_JSON }}
 #        This form of referencing should ideally work but for some reason, the data field is not evening showing up in the logs  
            
