name: test-POST 
on: [push]
jobs:
  post_mappings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Request action 
        uses: fjogeleit/http-request-action@master
        with: 
          url: 'https://tumgi3.free.beeceptor.com/my/api/path'
          method: 'POST'
          data: '{ "key": "value" }'
      
      - run: cd "${GITHUB_WORKSPACE}"
