name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          MAPPING_JSON: ''
      
  store_mapping:
    name: store variable
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: step two
      run: |
          MAPPING_JSON=$(cat ${GITHUB_WORKSPACE}/mappings.json } | jq .)
          echo $MAPPING_JSON
  
  post_mapping:
    runs-on: ubuntu-latest
    steps:
    - name: post mapping
      uses: fjogeleit/http-request-action@master
      with: 
        #url: "https://tumgi3.free.beeceptor.com/my/api/path"
        url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
        method: 'POST'
        #contentType: application/json
        #data: '{}'
        files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
               
  test_job:             
    runs-on: ubuntu-latest
    needs: [checkout, store_mapping]
    steps:
    - name: Test step
      run: |
          echo $MAPPING_JSON
          printenv
