name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v2
      - run: cd "${GITHUB_WORKSPACE}"
      
      - name: Request action 
        uses: fjogeleit/http-request-action@master
        with: 
          url: 'https://tumgi3.free.beeceptor.com/my/api/path'
          method: 'POST'
            #          data: '{ "key": "value" }'
          file: ${GITHUB_WORKSPACE}/mappings.json
