name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: post mapping      
        uses: fjogeleit/http-request-action@master
        with: 
          url: "https://tumgi3.free.beeceptor.com/my/api/path"
            #url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
          method: 'POST'
          contentType: application/json
          data: 
          files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
