name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        run: JSONdata=$(cat ./mappings.json | jq .)       
#        with: 
#          ref: ${{ github.workspace }}
      
  post:
    runs-on: ubuntu-latest    
        name: post mappings to nodered
        needs: checkout
        uses: fjogeleit/http-request-action@master
        with: 
          url: "https://tumgi3.free.beeceptor.com/my/api/path"
            #url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
          method: 'POST'
          contentType: application/json
          data: JSONdata
            #files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
