name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
  
  set_env:
  - name: set environment variables
    runs-on: ubuntu-latest
    uses: allenevans/set-env@v2.0.0
    with:
      MAPPING_JSON: ""
  
  store_mapping:
  - name: store variable
    runs-on: ubuntu-latest
    needs: [set_env]
    run: |
          MAPPING_JSON=$(cat ./mappings.json | jq .)
          echo $MAPPING_JSON
          printenv
  
  post_mapping:
  - name: post mapping
    runs-on: ubuntu-latest
        uses: fjogeleit/http-request-action@master
        with: 
          #url: "https://tumgi3.free.beeceptor.com/my/api/path"
          url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
          method: 'POST'
            #contentType: application/json
          data: 
          files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
               
  test_job:             
  - name: Test step
    runs-on: ubuntu-latest
    needs: [set_env, store_mapping]
    run: |
          echo $MAPPING_JSON
          printenv
