name: test-POST 
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
    
      - name: set global variable
        id: step_one
        run: echo "mapping_json=temp" >> $GITHUB_ENV
        
      - name: test global variable
        id: step_two
        run: echo "${{ env.mapping_json }}"
        
#      - name: set environment variables
#        uses: allenevans/set-env@v2.0.0
#        with:
#          MAPPING_JSON: 'start'
      
  store_mapping:
    name: store variable
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: step two
      run: |
          ls -ltr
          cat $GITHUB_WORKSPACE/mappings.json
          ls $GITHUB_WORKSPACE
          echo ${{ env.mapping_json }}
#          ${{ env.mapping_json }} = $(cat ${GITHUB_WORKSPACE}/mappings.json | jq .)
  post_mapping:
    runs-on: ubuntu-latest
    steps:
    - name: post mapping
      uses: fjogeleit/http-request-action@master
      with: 
        #url: "https://tumgi3.free.beeceptor.com/my/api/path"
        url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
        method: 'POST'
        #contentType: application/json
        #data: '{}'
        files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
               
  test_job:             
    runs-on: ubuntu-latest
    needs: [checkout, store_mapping]
    steps:
    - name: Test step
      run: |
          echo $MAPPING_JSON
          printenv
