name: test-POST 
on: [push]
#env:
#  mapping_json: $((cat ./mappings.json) 2>&1)
#  mapping_json: 'temporar'
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: step_two
        run: |
          echo "MAPPING_JSON=$((cat ./mappings.json) 2>&1)" >> $GITHUB_ENV

#            echo ${{ env.mapping_json }}
      - name: Export variable for next jobs
        uses: UnlyEd/github-action-store-variable@v2.1.0 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          # Persist (store) our MAGIC_NUMBER ENV variable into our store, for the next jobs
          variables: |
            MAPPING_JSON=${{ env.MAGIC_NUMBER}}          
      - name: post mapping
        uses: fjogeleit/http-request-action@master
        with: 
          url: "https://tumgi3.free.beeceptor.com/my/api/path"
   #       url: "https://gi3.gis.lrg.tum.de/nodered/mappings"
          method: 'POST'
#          data: $(cat ./mappings.json)
          data: ${{ env.MAPPING_JSON }}

   #       files: '{ "file": "${{ github.workspace  }}/mappings.json" }'
          #contentType: application/json
    #        data: ${{ env.mapping_json }}

#  store_mapping:
#    name: store variable
#    runs-on: ubuntu-latest
#    needs: [checkout]
#    steps:
#    - name: step two
#      run: |
#          echo ${{ env.mapping_json }}
#          cat @mappings.json
#          cat $GITHUB_WORKSPACE/mappings.json
#          ${{ env.mapping_json }} = $(cat ${GITHUB_WORKSPACE}/mappings.json | jq .)
#  post_mapping:
#    runs-on: ubuntu-latest
#    steps:


               
#  test_job:             
#    runs-on: ubuntu-latest
#    needs: [checkout, post_mapping]
#    steps:
#    - name: Test step
#      run: |
#          echo ${{ env.mapping_json }}
#          printenv
